-- Insert sample categories
INSERT INTO [dbo].[Category] 
([Name], [Description], [ParentCategoryId], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [IsDeleted], [DeletedOn], [DeletedBy])
VALUES
('Electronics', 'Devices, gadgets, and accessories', NULL, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Home Appliances', 'Household electronic appliances', NULL, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Fashion', 'Clothing and accessories for men and women', NULL, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Sports & Outdoors', 'Equipment and gear for sports and outdoor activities', NULL, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Books', 'Printed and digital books across genres', NULL, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL);

-- Insert 20 sample products
INSERT INTO [dbo].[Product] 
([Name], [OrderId], [CategoryId], [StockQuantity], [Price], [Description], [ImageUrl], [IsActive], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [IsDeleted], [DeletedOn], [DeletedBy])
VALUES
('iPhone 14 Pro', NULL, 1, 50, 999.99, 'Apple smartphone with A16 Bionic chip and 48MP camera', 'https://m.media-amazon.com/images/I/61qD-qiTKEL._AC_SX569_.jpg|https://m.media-amazon.com/images/I/817WqZsxjWL._AC_SX569_.jpg|https://m.media-amazon.com/images/I/61VuVU94RnL._AC_SX569_.jpg|https://m.media-amazon.com/images/I/71SfvBP1gBL._AC_SX569_.jpg|https://m.media-amazon.com/images/I/61EzF5tclRL._AC_SX569_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Samsung Galaxy S24', NULL, 1, 60, 899.99, 'Samsung flagship smartphone with Snapdragon 8 Gen 2', 'https://m.media-amazon.com/images/I/71WkqFssobL._AC_SX569_.jpg|https://m.media-amazon.com/images/I/71ZizBBjvBL._AC_SX569_.jpg|https://m.media-amazon.com/images/I/71xefLMjjaL._AC_SX569_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Sony WH-1000XM5 Headphones', NULL, 1, 80, 349.99, 'Noise-cancelling wireless over-ear headphones', 'https://m.media-amazon.com/images/I/61EZ0Dhw0fL._AC_SY450_.jpg|https://m.media-amazon.com/images/I/514bkhGFloL._AC_SY450_.jpg|https://m.media-amazon.com/images/I/61qmRVWOoML._AC_SY450_.jpg|https://m.media-amazon.com/images/I/31vqRm+yJCL._AC_SL1200_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Dell XPS 13 Laptop', NULL, 1, 30, 1299.99, 'Ultrabook with Intel i7 processor and 16GB RAM', 'https://m.media-amazon.com/images/I/51Iex1kndNL._AC_SX569_.jpg|https://m.media-amazon.com/images/I/31aYYX16R8L._AC_SX569_.jpg|https://m.media-amazon.com/images/I/31RjtfSnNHL._AC_SX569_.jpg|https://m.media-amazon.com/images/I/51pSUeltc1L._AC_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('LG OLED C2 TV 55"', NULL, 1, 20, 1499.99, '55-inch 4K OLED smart TV with HDR support', 'https://m.media-amazon.com/images/I/51okbef8aqL._AC_SL1070_.jpg|https://m.media-amazon.com/images/I/71NI2izxUtL._AC_SY450_.jpg|https://m.media-amazon.com/images/I/716dCkP7UeL._AC_SY450_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),

('Dyson V15 Detect Vacuum', NULL, 2, 40, 749.99, 'Cordless vacuum cleaner with laser dust detection', 'https://m.media-amazon.com/images/I/41QSi9aq+oL._AC_SX569_.jpg|https://m.media-amazon.com/images/I/41Ed0TfrQxL._AC_SX569_.jpg|https://m.media-amazon.com/images/I/61Fuq7wGiFL._AC_SX425_.jpg|', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Instant Pot Duo 7-in-1', NULL, 2, 70, 99.99, 'Multi-use pressure cooker, slow cooker, and more', 'https://m.media-amazon.com/images/I/51x6P+jw2UL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/81cNojLpjSL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/81PZzqig7dL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/61qKLYAd92L._AC_SX425_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Philips Air Fryer XXL', NULL, 2, 50, 299.99, 'Large-capacity air fryer with fat removal technology', 'https://m.media-amazon.com/images/I/51BJUquJQ5L.__AC_SX300_SY300_QL70_ML2_.jpg|https://m.media-amazon.com/images/I/61-Bsm3qvlL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/6110n9glflL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/61xEGP8s2fL._AC_SX425_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('KitchenAid Stand Mixer', NULL, 2, 25, 449.99, 'Iconic stand mixer with multiple attachments', 'https://m.media-amazon.com/images/I/61aY-ogYC8L.__AC_SY300_SX300_QL70_ML2_.jpg|https://m.media-amazon.com/images/I/61FOc96wG2L._AC_SX425_.jpg|https://m.media-amazon.com/images/I/51iphXmMScL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/514W6QB2a0L._AC_SX425_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),

('Men Leather Jacket', NULL, 3, 40, 199.99, 'Genuine leather biker-style jacket', 'https://m.media-amazon.com/images/I/51oOypZWilL._AC_SY445_.jpg|https://m.media-amazon.com/images/I/51P+SLNxU1L._AC_SY445_.jpg|https://m.media-amazon.com/images/I/51as4VS6oXL._AC_SY445_.jpg|https://m.media-amazon.com/images/I/51GPNHili4L._AC_SY445_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Women Summer Dress', NULL, 3, 60, 59.99, 'Lightweight floral print dress', 'https://m.media-amazon.com/images/I/41GbBS9BcYL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/4187+gR2zrL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/51LfgxlTTIL._AC_SX425_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Nike Air Max 270', NULL, 3, 80, 129.99, 'Sport-inspired casual sneakers', 'https://m.media-amazon.com/images/I/61Xg4CYYRML._AC_SY535_.jpg|https://m.media-amazon.com/images/I/71N+ILCDENL._AC_SY535_.jpg|https://m.media-amazon.com/images/I/61ueDAndGXL._AC_SY535_.jpg|https://m.media-amazon.com/images/I/71HD9dd14JL._AC_SY535_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Adidas Hoodie', NULL, 3, 100, 69.99, 'Soft cotton pullover hoodie', 'https://m.media-amazon.com/images/I/71VzglPCtcL._AC_SX385_.jpg|https://m.media-amazon.com/images/I/51o-dJHvwVL._AC_SX466_.jpg|https://m.media-amazon.com/images/I/81e-o1MxwVL._AC_SX385_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),

('Wilson Tennis Racket', NULL, 4, 35, 159.99, 'Professional-grade tennis racket', 'https://m.media-amazon.com/images/I/61TKOHMrE5L.__AC_SX300_SY300_QL70_ML2_.jpg|https://m.media-amazon.com/images/I/61kTK9tMU9L._AC_SX425_.jpg|https://m.media-amazon.com/images/I/61+ZEdBhhcL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/7169ryiKhNL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/71lfYDXgX+L._AC_SX425_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Yoga Mat Pro', NULL, 4, 60, 49.99, 'Non-slip thick yoga mat for home and studio', 'https://m.media-amazon.com/images/I/61skBkvby4L.__AC_SY300_SX300_QL70_ML2_.jpg|https://m.media-amazon.com/images/I/21truBO5jgL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/31apI66ZU3L._AC_SX425_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Camping Tent 4-Person', NULL, 4, 25, 199.99, 'Waterproof and windproof family tent', 'https://m.media-amazon.com/images/I/61uE5Rlh7ZL.__AC_SX300_SY300_QL70_ML2_.jpg|https://m.media-amazon.com/images/I/81jvUcEP+dL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/813rdwq3VxL._AC_SX425_.jpg|https://m.media-amazon.com/images/I/611aWOi7m0L._AC_SX425_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),

('The Great Gatsby', NULL, 5, 100, 14.99, 'Classic novel by F. Scott Fitzgerald', 'https://m.media-amazon.com/images/I/81K1jbUMmFL._SY342_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Atomic Habits', NULL, 5, 80, 21.99, 'Self-help book by James Clear on building good habits', 'https://m.media-amazon.com/images/I/61Ki8s31KtL.__AC_SY300_SX300_QL70_ML2_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Harry Potter Box Set', NULL, 5, 50, 89.99, 'Complete collection of Harry Potter books', 'https://m.media-amazon.com/images/I/41C3OItzggL._SX342_SY445_.jpg|https://m.media-amazon.com/images/I/71n2ruQNcpL._SY342_.jpg|https://m.media-amazon.com/images/I/81vk-9zjgpL._SL1500_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL),
('Becoming', NULL, 5, 70, 19.99, 'Memoir by Michelle Obama', 'https://m.media-amazon.com/images/I/81cJTmFpG-L._SY342_.jpg', 1, 'admin', GETDATE(), NULL, NULL, 0, NULL, NULL);
